# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c1096f381cadb2652623c0a0adf6d305a71dfecfaaf676177c27cf3d9f488065544f44c280edbdce7c6209faa0e2e039830ce6d07cbcb5799289e5d5fb91807

test:
  secret_key_base: 7985ed89687c0ddc3efca8ebee0385395c288412744b5b1c6bb61c392052517a01f32d5a17aa679bcbd900dde017618e164875f66dfeeb1383cf24f5e3a25288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
